#!/bin/bash

# ハッシュが作れる？に回リストを読み込みたくない...
# case分の方がいいかもしれない

# -short (短い説明を入れる)
# -jp (日本語の説明)

# for loopでは、スペースを入れてしまうので、次の行が入ってあると、それは解決されます
IFS=$'\n'

# Sはstatusesのこと
S['200']='200: success'
S['404']='404: forbidden'

for i in ${S[@]}; do
  echo "${i}"
done

if [ -z $1 ]; then
  echo 'please use -l for the whole list'
  echo 'please use -h for help'
fi

if [ $1 ] && [ $1 == '404' ]; then
  echo '404: forbidden'
elif [ $1 ] && [ $1 == '200' ]; then
  echo '200: success'
fi
